name: nyc_crashes
version: "1.0.0"
config-version: 2

profile: nyc_crashes

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  nyc_crashes:
    staging:
      +severity: warn
      +meta:
        dagster:
          group: staging
      +materialized: table
      +schema: staging
    clean:
      +meta:
        dagster:
          group: staging
      +materialized: table
      +schema: staging
    quarantine:
      +meta:
          dagster:
            group: quarantine
      +materialized: table
      +schema: quarantine
    core:
      +meta:
          dagster:
            group: core
      +materialized: table
      +schema: core
    marts:
      +meta:
          dagster:
            group: marts
      +materialized: table
      +schema: marts
    audit:
      +meta:
          dagster:
            group: audit
      +materialized: table
      +schema: audit

tests:
  nyc_crashes:
    staging:
      +severity: warn
