select
    collision_id::bigint                            as collision_id,
    crash_date::date                                as crash_date,
    crash_time::time                                as crash_time,
    borough,
    zip_code,
    latitude::numeric                               as latitude,
    longitude::numeric                              as longitude,
    location,
    on_street_name,
    cross_street_name,
    off_street_name,
    contributing_factor_vehicle_1,
    contributing_factor_vehicle_2,
    contributing_factor_vehicle_3,
    contributing_factor_vehicle_4,
    contributing_factor_vehicle_5,
    vehicle_type_code_1,
    vehicle_type_code_2,
    vehicle_type_code_3,
    vehicle_type_code_4,
    vehicle_type_code_5,
    number_of_persons_injured::integer              as persons_injured,
    number_of_persons_killed::integer               as persons_killed,
    number_of_pedestrians_injured::integer          as pedestrians_injured,
    number_of_pedestrians_killed::integer           as pedestrians_killed,
    number_of_cyclist_injured::integer              as cyclist_injured,
    number_of_cyclist_killed::integer               as cyclist_killed,
    number_of_motorist_injured::integer             as motorist_injured,
    number_of_motorist_killed::integer              as motorist_killed
from {{ source('raw', 'crashes') }}
