select
    {{ dbt.safe_cast('collision_id', 'bigint') }}                       as collision_id,
    {{ dbt.safe_cast('crash_date', 'date') }}                           as crash_date,
    {{ dbt.safe_cast('crash_time', 'time') }}                           as crash_time,
    nullif(trim(lower(borough)), '')                                    as borough,
    nullif(trim(lower(zip_code)), '')                                   as zip_code,
    {{ dbt.safe_cast('latitude', 'numeric') }}                          as latitude,
    {{ dbt.safe_cast('longitude', 'numeric') }}                         as longitude,
    nullif(trim(lower(location)), '')                                   as location,
    nullif(trim(lower(on_street_name)), '')                             as on_street_name,
    nullif(trim(lower(cross_street_name)), '')                          as cross_street_name,
    nullif(trim(lower(off_street_name)), '')                            as off_street_name,
    nullif(trim(lower(contributing_factor_vehicle_1)), '')              as contributing_factor_vehicle_1,
    nullif(trim(lower(contributing_factor_vehicle_2)), '')              as contributing_factor_vehicle_2,
    nullif(trim(lower(contributing_factor_vehicle_3)), '')              as contributing_factor_vehicle_3,
    nullif(trim(lower(contributing_factor_vehicle_4)), '')              as contributing_factor_vehicle_4,
    nullif(trim(lower(contributing_factor_vehicle_5)), '')              as contributing_factor_vehicle_5,
    nullif(trim(lower(vehicle_type_code_1)), '')                        as vehicle_type_code_1,
    nullif(trim(lower(vehicle_type_code_2)), '')                        as vehicle_type_code_2,
    nullif(trim(lower(vehicle_type_code_3)), '')                        as vehicle_type_code_3,
    nullif(trim(lower(vehicle_type_code_4)), '')                        as vehicle_type_code_4,
    nullif(trim(lower(vehicle_type_code_5)), '')                        as vehicle_type_code_5,
    {{ dbt.safe_cast('number_of_persons_injured', 'integer') }}         as persons_injured,
    {{ dbt.safe_cast('number_of_persons_killed', 'integer') }}          as persons_killed,
    {{ dbt.safe_cast('number_of_pedestrians_injured', 'integer') }}     as pedestrians_injured,
    {{ dbt.safe_cast('number_of_pedestrians_killed', 'integer') }}      as pedestrians_killed,
    {{ dbt.safe_cast('number_of_cyclist_injured', 'integer') }}         as cyclist_injured,
    {{ dbt.safe_cast('number_of_cyclist_killed', 'integer') }}          as cyclist_killed,
    {{ dbt.safe_cast('number_of_motorist_injured', 'integer') }}        as motorist_injured,
    {{ dbt.safe_cast('number_of_motorist_killed', 'integer') }}         as motorist_killed
from {{ source('raw', 'crashes') }}
